---
- name: MongoDB, Nginx, PHP7.1, and Laravel Deployment
  hosts: webserver
  remote_user:  '{{ ssh_remote_user }}'
  # sudo privileges
  become_method: sudo
  become: yes # activate privilege escalation

  vars_files:
    - vars.yml
  
  # tasks:
    # Testing
    # - name: test connection
    #   ping:
    
  roles:
    - mongodb
    - nginx
    - php
    - laravel
  
  handlers:
    - name: restart ufw
      service: 
        name: ufw 
        state: restarted
    
    - name: restart nginx
      service: 
        name: nginx 
        state: restarted

    - name: restart php7.1-fpm
      service:
        name: php7.1-fpm 
        state: restarted